import { defineConfig } from "@kubb/core";
import { pluginOas } from "@kubb/plugin-oas";
import { pluginTs } from "@kubb/plugin-ts";
import { pluginClient } from "@kubb/plugin-client";

export default defineConfig({
  input: {
    // Path to the OpenAPI spec generated by tsoa from the server
    path: "../server/src/generated/swagger.json",
  },
  output: {
    path: "src/generated",
    clean: true,
    extension: { ".ts": ".js" },
  },
  plugins: [
    pluginOas(),
    pluginTs({
      output: {
        path: "types",
      },
    }),
    pluginClient({
      output: {
        path: "clients",
      },
    }),
  ],
});
