/**
 * @fileoverview This script generates the API boilerplate code from the function definitions in the `actions` folder.
 * It should be executed at build time, as the generated files are used to a) present the API as openapi.json and b) provide the registry that maps API endpoints (via WebSocket) to the actual function implementations.
 */

import { Project, TypeFormatFlags } from "ts-morph";
import * as fs from "fs";
import * as path from "path";

console.log("Generating API...");

const project = new Project();
project.addSourceFilesAtPaths("src/actions/**/*.ts");
console.log(`Identified action files: ${project.getSourceFiles().map((f) => f.getBaseName()).join(", ")}`);

const openApiSpec = {
    openapi: "3.0.0",
    info: {
        title: "PremiereRemote",
        version: "3.0.0",
        description: "Generated API specification for PremiereRemote",
    },
    paths: {},
};
let registryFileContent = `// This file is auto-generated by \`scripts/generate-api.js\`. Do not edit manually. Changes will be overwritten.\n\nexport const apiRegistry = {\n`;

for (const sourceFile of project.getSourceFiles()) {
    const functions = sourceFile.getFunctions();

    for (const func of functions) {
        console.log(`Processing function: ${func.getName()}`);
        console.log(func.isExported() ? "Exported" : "Not exported");
        console.log(func.getJsDocs.length > 0 ? "Has JSDoc" : "No JSDoc");
    }
}