/**
 * @fileoverview This script generates the API boilerplate code from the function definitions in the `actions` folder.
 * It should be executed at build time, as the generated files are used to a) present the API as openapi.json and b) provide the registry that maps API endpoints (via WebSocket) to the actual function implementations.
 */

import { Project, TypeFormatFlags } from "ts-morph";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

console.log("Generating API...");
const scriptsDirectoryName = path.dirname(fileURLToPath(import.meta.url));
const { version } = JSON.parse(fs.readFileSync(path.resolve(scriptsDirectoryName, "../package.json"), "utf-8"));

const project = new Project();
project.addSourceFilesAtPaths("src/actions/**/*.ts");
console.log(
    `Identified action files: ${project
        .getSourceFiles()
        .map((f) => f.getBaseName())
        .join(", ")}`,
);

const openApiPaths = {};
let registryImports = "/* eslint-disable */\n// This file is auto-generated by `scripts/generate-api.js`. Do not edit manually. Changes will be overwritten.\n\n";
let registryEntries = "";
let actionCount = 0;
const tags = new Set();

for (const sourceFile of project.getSourceFiles()) {
    const namespace = path
        .relative(path.resolve("src/actions"), sourceFile.getFilePath())
        .replace(/\\/g, "/")
        .replace(/\.ts$/, "");
    const namespaceAlias = namespace.replace(/\//g, "__");
    const importPath = path
        .relative(path.resolve("src/generated"), sourceFile.getFilePath())
        .replace(/\\/g, "/")
        .replace(/\.ts$/, ".js");

    const actions = sourceFile
        .getFunctions()
        .filter((f) => f.isExported() && f.getJsDocs()[0]?.getDescription().trim());

    console.log(`${namespace}: ${actions.length} action(s)`);

    for (const func of actions) {
        const name = func.getName();
        actionCount++;

        const jsDoc = func.getJsDocs()[0];
        const description = jsDoc.getDescription().trim();
        const returnsComment = String(
            jsDoc.getTags().find((t) => ["returns", "return"].includes(t.getTagName()))?.getComment() ?? ""
        ).trim();

        const properties = {};
        const required = new Set();
        for (const param of func.getParameters()) {
            const paramName = param.getName();
            const paramType = param.getType().getText(undefined, TypeFormatFlags.NoTruncation);
            const knownType = { string: "string", number: "number", boolean: "boolean" }[paramType];
            if (!knownType) console.warn(`  Warning: unsupported type "${paramType}" (${name}.${paramName}), falling back to string`);
            properties[paramName] = { type: knownType ?? "string" };
            if (!param.isOptional()) required.add(paramName);
        }

        const returnTypeText = func.getReturnType().getText(undefined, TypeFormatFlags.NoTruncation);
        const unwrappedReturn = (returnTypeText.match(/^Promise<(.+)>$/s)?.[1] ?? returnTypeText)
            .replace(/\s*\|\s*(null|undefined)\s*/g, "")
            .trim();
        const returnSchema =
            unwrappedReturn === "void" ? null
            : unwrappedReturn === "string" ? { type: "string" }
            : unwrappedReturn === "number" ? { type: "number" }
            : unwrappedReturn === "boolean" ? { type: "boolean" }
            : unwrappedReturn.endsWith("[]") ? { type: "array" }
            : { type: "object" };

        const tag = namespace;
        tags.add(tag);
        openApiPaths[`/${namespace}/${name}`] = {
            get: {
                summary: description,
                operationId: `${namespace}/${name}`,
                tags: [tag],
                parameters: Object.entries(properties).map(([paramName, schema]) => ({
                    name: paramName,
                    in: "query",
                    required: required.has(paramName),
                    schema,
                })),
                responses: {
                    "200": {
                        description: returnsComment || "Success",
                        ...(returnSchema
                            ? { content: { "application/json": { schema: returnSchema } } }
                            : {}),
                    },
                    "500": {
                        description: "Internal error",
                        content: {
                            "application/json": {
                                schema: {
                                    type: "object",
                                    properties: { error: { type: "string" } },
                                    required: ["error"],
                                },
                            },
                        },
                    },
                },
            },
        };

        registryImports += `import { ${name} as ${namespaceAlias}__${name} } from "${importPath}";\n`;
        registryEntries += `    "${namespace}/${name}": ${namespaceAlias}__${name},\n`;
    }
}

const openApiDoc = {
    openapi: "3.0.0",
    info: {
        title: "PremiereRemote",
        version,
        description: "Generated API specification for PremiereRemote",
    },
    tags: [...tags].map((t) => ({ name: t })),
    paths: openApiPaths,
};

const serverOutPath = path.resolve(scriptsDirectoryName, "../../server/openapi.json");
const registryOutPath = path.resolve(scriptsDirectoryName, "../src/generated/registry.ts");

fs.mkdirSync(path.dirname(serverOutPath), { recursive: true });
fs.mkdirSync(path.dirname(registryOutPath), { recursive: true });

fs.writeFileSync(serverOutPath, JSON.stringify(openApiDoc, null, 2));
fs.writeFileSync(
    registryOutPath,
    registryImports + `\nexport const apiRegistry: Record<string, Function> = {\n${registryEntries}};\n`
);

console.log(`Done: ${actionCount} action(s) total`);

