/**
 * @fileoverview This script generates the API boilerplate code from the function definitions in the `actions` folder.
 * It should be executed at build time, as the generated files are used to a) present the API as openapi.json and b) provide the registry that maps API endpoints (via WebSocket) to the actual function implementations.
 */

import { Project, TypeFormatFlags } from "ts-morph";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

console.log("Generating PremiereRemote API");
const scriptsDirectoryName = path.dirname(fileURLToPath(import.meta.url));
const { version } = JSON.parse(
    fs.readFileSync(
        path.resolve(scriptsDirectoryName, "../package.json"),
        "utf-8",
    ),
);

const project = new Project();
project.addSourceFilesAtPaths("src/actions/**/*.ts");
const sourceFiles = project.getSourceFiles();

const openApiPaths = {};
let registryImports =
    "/* eslint-disable */\n// This file is auto-generated by `scripts/generate-api.js`. Do not edit manually. Changes will be overwritten.\n\n";
let registryEntries = "";
let actionCount = 0;
const tags = new Set();

for (const sourceFile of sourceFiles) {
    const namespace = path
        .relative(path.resolve("src/actions"), sourceFile.getFilePath())
        .replace(/\\/g, "/")
        .replace(/\.ts$/, "");
    const namespaceAlias = namespace.replace(/\//g, "__");
    const importPath = path
        .relative(path.resolve("src/generated"), sourceFile.getFilePath())
        .replace(/\\/g, "/")
        .replace(/\.ts$/, ".js");

    // Actions, provided by the API, are exported functions with a non-empty JSDoc description.
    const actions = sourceFile
        .getFunctions()
        .filter(
            (f) => f.isExported() && f.getJsDocs()[0]?.getDescription().trim(),
        );
    console.log(
        `➡️ ${path.relative(
            path.resolve("src/actions"),
            sourceFile.getFilePath(),
        )}`,
    );

    for (const action of actions) {
        const hasParams = action.getParameters().length > 0;
        const name = action.getName();
        console.log(`   • ${name}(${hasParams ? "..." : ""})`);
        actionCount++;

        const jsDoc = action.getJsDocs()[0];
        const descriptionDoc = jsDoc.getDescription().trim();
        const returnsDoc = String(
            jsDoc
                .getTags()
                .find((t) => ["returns", "return"].includes(t.getTagName()))
                ?.getComment() ?? "",
        ).trim();

        const properties = {};
        const required = new Set();
        for (const param of action.getParameters()) {
            const paramName = param.getName();
            const paramType = param
                .getType()
                .getText(undefined, TypeFormatFlags.NoTruncation);

            const knownType = {
                string: "string",
                number: "number",
                boolean: "boolean",
            }[paramType];
            if (!knownType)
                console.warn(
                    `   ⚠️ Warning: unsupported parameter type "${paramType}", falling back to string`,
                );

            const paramDoc = String(
                jsDoc
                    .getTags()
                    .find(
                        (t) =>
                            t.getTagName() === "param" &&
                            t.getName() === paramName,
                    )
                    ?.getComment() ?? "",
            ).trim();
            if (!paramDoc)
                console.warn(
                    `   ⚠️ Warning: missing @param description for "${paramName}", parameter description will be empty`,
                );

            properties[paramName] = {
                type: knownType ?? "string",
                ...(paramDoc ? { description: paramDoc } : {}),
            };
            if (!param.isOptional()) required.add(paramName);
        }

        const returnType = action
            .getReturnType()
            .getText(undefined, TypeFormatFlags.NoTruncation);
        const unwrappedReturn = (
            returnType.match(/^Promise<(.+)>$/s)?.[1] ?? returnType
        )
            .replace(/\s*\|\s*(null|undefined)\s*/g, "")
            .trim();
        let returnSchema;
        switch (unwrappedReturn) {
            case "void":
                returnSchema = null;
                break;
            case "string":
                returnSchema = { type: "string" };
                break;
            case "number":
                returnSchema = { type: "number" };
                break;
            case "boolean":
                returnSchema = { type: "boolean" };
                break;
            default:
                returnSchema = unwrappedReturn.endsWith("[]")
                    ? { type: "array" }
                    : { type: "object" };
        }

        if (!returnsDoc && unwrappedReturn !== "void")
            console.warn(
                `   ⚠️ Warning: missing @returns JSDoc, response description will be empty`,
            );

        tags.add(namespace);
        openApiPaths[`/${namespace}/${name}`] = {
            get: {
                summary: descriptionDoc,
                operationId: `${namespace}/${name}`,
                tags: [namespace],
                parameters: Object.entries(properties).map(
                    ([paramName, { description: paramDesc, ...schema }]) => ({
                        name: paramName,
                        in: "query",
                        required: required.has(paramName),
                        ...(paramDesc ? { description: paramDesc } : {}),
                        schema,
                    }),
                ),
                responses: {
                    200: {
                        description: returnsDoc || "Success",
                        ...(returnSchema
                            ? {
                                  content: {
                                      "application/json": {
                                          schema: returnSchema,
                                      },
                                  },
                              }
                            : {}),
                    },
                    500: {
                        description: "Internal error",
                        content: {
                            "application/json": {
                                schema: {
                                    type: "object",
                                    properties: { error: { type: "string" } },
                                    required: ["error"],
                                },
                            },
                        },
                    },
                },
            },
        };

        registryImports += `import { ${name} as ${namespaceAlias}__${name} } from "${importPath}";\n`;
        registryEntries += `    "${namespace}/${name}": ${namespaceAlias}__${name},\n`;
    }
}

const openApiDoc = {
    openapi: "3.0.0",
    info: {
        title: "PremiereRemote",
        version,
        description: "Generated API specification for PremiereRemote",
    },
    tags: [...tags].map((t) => ({ name: t })),
    paths: openApiPaths,
};

const serverOutPath = path.resolve(
    scriptsDirectoryName,
    "../../server/openapi.json",
);
const registryOutPath = path.resolve(
    scriptsDirectoryName,
    "../src/generated/registry.ts",
);

fs.mkdirSync(path.dirname(serverOutPath), { recursive: true });
fs.mkdirSync(path.dirname(registryOutPath), { recursive: true });

fs.writeFileSync(serverOutPath, JSON.stringify(openApiDoc, null, 2));
fs.writeFileSync(
    registryOutPath,
    registryImports +
        `\nexport const apiRegistry: Record<string, Function> = {\n${registryEntries}};\n`,
);

console.log(
    `✅ Done: ${sourceFiles.length} action file(s), ${actionCount} endpoint(s) total`,
);
